name: NodeJS with Webpack

on:
  workflow_dispatch:

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM Dependencies
        run: |
          npm install
          npm install -g vsce

      - name: Build and Package
        run: |
          npx webpack
          vsce package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: VSIX
          path: ./*.vsix
          if-no-files-found: error
